// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpnc2ksWi07T7_gRwU6uP357k5Maes4qU',
    appId: '1:1061552730557:web:14a6345f2ef65c55c9e2d4',
    messagingSenderId: '1061552730557',
    projectId: 'truckfleet-app',
    authDomain: 'truckfleet-app.firebaseapp.com',
    storageBucket: 'truckfleet-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACTwITgRrZ1AExuuyo-t3YKIca3v6oDWE',
    appId: '1:1061552730557:android:1cfef9346b8a6319c9e2d4',
    messagingSenderId: '1061552730557',
    projectId: 'truckfleet-app',
    storageBucket: 'truckfleet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpXaJtxnVtf2ZQso-gsuv35kQ01UlNdL0',
    appId: '1:1061552730557:ios:2487e1b7be1a8ec9c9e2d4',
    messagingSenderId: '1061552730557',
    projectId: 'truckfleet-app',
    storageBucket: 'truckfleet-app.firebasestorage.app',
    iosBundleId: 'com.example.truckFleet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpXaJtxnVtf2ZQso-gsuv35kQ01UlNdL0',
    appId: '1:1061552730557:ios:2487e1b7be1a8ec9c9e2d4',
    messagingSenderId: '1061552730557',
    projectId: 'truckfleet-app',
    storageBucket: 'truckfleet-app.firebasestorage.app',
    iosBundleId: 'com.example.truckFleet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpnc2ksWi07T7_gRwU6uP357k5Maes4qU',
    appId: '1:1061552730557:web:57b7153b7c06f974c9e2d4',
    messagingSenderId: '1061552730557',
    projectId: 'truckfleet-app',
    authDomain: 'truckfleet-app.firebaseapp.com',
    storageBucket: 'truckfleet-app.firebasestorage.app',
  );
}
